import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Beers from '../../../components/Beers/Beers'
import Header from '../../../components/Header/Header'
import Search from '../../../components/Search/Search'
import styles from '../../../styles/BeersList.module.scss'

const BeersList: NextPage = () => {
    

    return (
        <div className={styles.container}>
        <Head>
            <title>Drunk Punk</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

            <Header/>

            <Search/>

            <Beers/>
        
        </main>

        <footer className={styles.footer}>

        </footer>
        </div>
    )
}

export default BeersList
